// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStockDailyConcept = "stock_daily_concept"

// StockDailyConcept 概念-每日领涨股
type StockDailyConcept struct {
	ConceptCode         string    `gorm:"column:concept_code;type:varchar(10);primaryKey;comment:概念代码" json:"concept_code"`                               // 概念代码
	ConceptName         string    `gorm:"column:concept_name;type:varchar(50);not null;comment:概念名称" json:"concept_name"`                                 // 概念名称
	UpNumber            int64     `gorm:"column:up_number;type:int(11);not null;comment:上涨家数" json:"up_number"`                                           // 上涨家数
	DownNumber          int64     `gorm:"column:down_number;type:int(11);not null;comment:下跌家数" json:"down_number"`                                       // 下跌家数
	ConceptIncreaseRate float64   `gorm:"column:concept_increase_rate;type:decimal(8,2);not null;default:0.00;comment:概念涨幅" json:"concept_increase_rate"` // 概念涨幅
	ConceptRank         int64     `gorm:"column:concept_rank;type:int(11);not null;comment:涨幅排名" json:"concept_rank"`                                     // 涨幅排名
	StockName           string    `gorm:"column:stock_name;type:varchar(50);not null;comment:股票名称-领涨" json:"stock_name"`                                  // 股票名称-领涨
	IncreaseRate        float64   `gorm:"column:increase_rate;type:decimal(8,2);not null;default:0.00;comment:股票涨幅" json:"increase_rate"`                 // 股票涨幅
	TradingDate         time.Time `gorm:"column:trading_date;type:date;primaryKey;comment:交易日期" json:"trading_date"`                                      // 交易日期
	UpdatedAt           time.Time `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`                                           // 更新时间
}

// TableName StockDailyConcept's table name
func (*StockDailyConcept) TableName() string {
	return TableNameStockDailyConcept
}
