// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStockConceptList = "stock_concept_list"

// StockConceptList 概念成份股列表-A股
type StockConceptList struct {
	ConceptCode string    `gorm:"column:concept_code;type:varchar(10);not null;comment:概念代码" json:"concept_code"` // 概念代码
	ConceptName string    `gorm:"column:concept_name;type:varchar(50);not null;comment:概念名称" json:"concept_name"` // 概念名称
	StockCode   string    `gorm:"column:stock_code;type:varchar(10);primaryKey;comment:股票代码" json:"stock_code"`   // 股票代码
	StockName   string    `gorm:"column:stock_name;type:varchar(50);not null;comment:股票名称" json:"stock_name"`     // 股票名称
	CreatedAt   time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                               // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`           // 更新时间
}

// TableName StockConceptList's table name
func (*StockConceptList) TableName() string {
	return TableNameStockConceptList
}
