// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStockDailyIndustry = "stock_daily_industry"

// StockDailyIndustry 行业-每日领涨股
type StockDailyIndustry struct {
	IndustryName         string    `gorm:"column:industry_name;type:varchar(50);not null;comment:行业名称" json:"industry_name"`                                 // 行业名称
	IndustryCode         string    `gorm:"column:industry_code;type:varchar(10);primaryKey;comment:行业代码" json:"industry_code"`                               // 行业代码
	UpNumber             int64     `gorm:"column:up_number;type:int(11);not null;comment:上涨家数" json:"up_number"`                                             // 上涨家数
	DownNumber           int64     `gorm:"column:down_number;type:int(11);not null;comment:下跌家数" json:"down_number"`                                         // 下跌家数
	IndustryIncreaseRate float64   `gorm:"column:industry_increase_rate;type:decimal(8,2);not null;default:0.00;comment:行业涨幅" json:"industry_increase_rate"` // 行业涨幅
	IndustryRank         int64     `gorm:"column:industry_rank;type:int(11);not null;comment:涨幅排名" json:"industry_rank"`                                     // 涨幅排名
	StockName            string    `gorm:"column:stock_name;type:varchar(50);not null;comment:股票名称-领涨" json:"stock_name"`                                    // 股票名称-领涨
	IncreaseRate         float64   `gorm:"column:increase_rate;type:decimal(8,2);not null;default:0.00;comment:股票涨幅" json:"increase_rate"`                   // 股票涨幅
	TradingDate          time.Time `gorm:"column:trading_date;type:date;primaryKey;comment:交易日期" json:"trading_date"`                                        // 交易日期
	UpdatedAt            time.Time `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`                                             // 更新时间
}

// TableName StockDailyIndustry's table name
func (*StockDailyIndustry) TableName() string {
	return TableNameStockDailyIndustry
}
