// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStockIndustry = "stock_industry"

// StockIndustry 行业列表-A股
type StockIndustry struct {
	ID              int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`            // 主键ID
	IndustryName    string    `gorm:"column:industry_name;type:varchar(50);not null;comment:行业名称" json:"industry_name"`                   // 行业名称
	IndustryCode    string    `gorm:"column:industry_code;type:varchar(10);not null;comment:行业代码" json:"industry_code"`                   // 行业代码
	IsWatchIndustry int64     `gorm:"column:is_watch_industry;type:tinyint(4);not null;comment:自选行业标志(0-否 1-是)" json:"is_watch_industry"` // 自选行业标志(0-否 1-是)
	CreatedAt       time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                   // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`                               // 更新时间
}

// TableName StockIndustry's table name
func (*StockIndustry) TableName() string {
	return TableNameStockIndustry
}
