// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStock = "stock"

// Stock 股票列表-A股
type Stock struct {
	StockCode     string `gorm:"column:stock_code;type:varchar(10);primaryKey;comment:股票代码" json:"stock_code"`                                         // 股票代码
	StockName     string `gorm:"column:stock_name;type:varchar(10);not null;comment:股票名称" json:"stock_name"`                                           // 股票名称
	Industry      string `gorm:"column:industry;type:varchar(50);not null;comment:行业" json:"industry"`                                                 // 行业
	IndustryCode  string `gorm:"column:industry_code;type:varchar(10);not null;comment:行业代码" json:"industry_code"`                                     // 行业代码
	Exchange      int64  `gorm:"column:exchange;type:tinyint(4);not null;comment:交易所(0-全部,1-深圳,2-上海,3-北京)" json:"exchange"`                            // 交易所(0-全部,1-深圳,2-上海,3-北京)
	MarketType    int64  `gorm:"column:market_type;type:tinyint(4);not null;comment:市场类别(0-全部,1-主板10%,2-创业板20%,3-科创板20%,4-北交所30%)" json:"market_type"` // 市场类别(0-全部,1-主板10%,2-创业板20%,3-科创板20%,4-北交所30%)
	IncreaseRange string `gorm:"column:increase_range;type:varchar(10);not null;comment:涨幅范围(10%,20%,30%)" json:"increase_range"`                      // 涨幅范围(10%,20%,30%)
	IsNewlyListed int64  `gorm:"column:is_newly_listed;type:tinyint(4);not null;comment:次新股(0-否 1-是) 上市时间一年以内" json:"is_newly_listed"`                 // 次新股(0-否 1-是) 上市时间一年以内
	ListingDate   int64  `gorm:"column:listing_date;type:bigint(20);not null;comment:上市日期" json:"listing_date"`                                        // 上市日期
	CreatedAt     int64  `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                                     // 创建时间
	UpdatedAt     int64  `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`                                                 // 更新时间
}

// TableName Stock's table name
func (*Stock) TableName() string {
	return TableNameStock
}
