// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStockStrong = "stock_strong"

// StockStrong 每日强势榜
type StockStrong struct {
	StockCode                    string    `gorm:"column:stock_code;type:varchar(10);primaryKey;comment:股票代码" json:"stock_code"`                                                        // 股票代码
	StockName                    string    `gorm:"column:stock_name;type:varchar(10);not null;comment:股票名称" json:"stock_name"`                                                          // 股票名称
	CirculatingMarketValue       float64   `gorm:"column:circulating_market_value;type:decimal(8,2);not null;default:0.00;comment:流通市值" json:"circulating_market_value"`                // 流通市值
	PlateType                    int64     `gorm:"column:plate_type;type:tinyint(4);not null;comment:盘股类型(0-全部,1-微小盘,2-小盘,3-中盘,4-大盘)" json:"plate_type"`                                // 盘股类型(0-全部,1-微小盘,2-小盘,3-中盘,4-大盘)
	VolumeRatio                  float64   `gorm:"column:volume_ratio;type:decimal(8,2);not null;default:0.00;comment:量比" json:"volume_ratio"`                                          // 量比
	TurnoverRate                 float64   `gorm:"column:turnover_rate;type:decimal(8,2);not null;default:0.00;comment:换手" json:"turnover_rate"`                                        // 换手
	IncreaseRate                 float64   `gorm:"column:increase_rate;type:decimal(8,2);not null;default:0.00;comment:涨幅" json:"increase_rate"`                                        // 涨幅
	CurrentPrice                 float64   `gorm:"column:current_price;type:decimal(8,2);not null;default:0.00;comment:现价" json:"current_price"`                                        // 现价
	NewHigh                      int64     `gorm:"column:new_high;type:tinyint(4);not null;comment:是否新高(0-否 1-是)" json:"new_high"`                                                      // 是否新高(0-否 1-是)
	UpdownType                   int64     `gorm:"column:updown_type;type:tinyint(4);primaryKey;comment:涨跌类型(0-全部,1-涨停股,2-跌停股,3-炸板股,4-强势股)" json:"updown_type"`                         // 涨跌类型(0-全部,1-涨停股,2-跌停股,3-炸板股,4-强势股)
	SealingFund                  float64   `gorm:"column:sealing_fund;type:decimal(10,2);not null;default:0.00;comment:封板资金" json:"sealing_fund"`                                       // 封板资金
	FirstSealingTime             string    `gorm:"column:first_sealing_time;type:varchar(10);not null;comment:首次封板时间" json:"first_sealing_time"`                                        // 首次封板时间
	LastSealingTime              string    `gorm:"column:last_sealing_time;type:varchar(10);not null;comment:最后封板时间" json:"last_sealing_time"`                                          // 最后封板时间
	BreakingBoardTimes           int64     `gorm:"column:breaking_board_times;type:tinyint(4);not null;comment:炸板次数" json:"breaking_board_times"`                                       // 炸板次数
	UpdownDays                   int64     `gorm:"column:updown_days;type:tinyint(4);not null;comment:涨停统计-天数" json:"updown_days"`                                                      // 涨停统计-天数
	UpdownTimes                  int64     `gorm:"column:updown_times;type:tinyint(4);not null;comment:涨停统计-次数" json:"updown_times"`                                                    // 涨停统计-次数
	ConsecutiveLimitUpDays       int64     `gorm:"column:consecutive_limit_up_days;type:tinyint(4);not null;comment:连板数" json:"consecutive_limit_up_days"`                              // 连板数
	SealingOrderTradingRatio     float64   `gorm:"column:sealing_order_trading_ratio;type:decimal(8,2);not null;default:0.00;comment:封单成交比" json:"sealing_order_trading_ratio"`         // 封单成交比
	SealingOrderCirculatingRatio float64   `gorm:"column:sealing_order_circulating_ratio;type:decimal(8,2);not null;default:0.00;comment:封单流通比" json:"sealing_order_circulating_ratio"` // 封单流通比
	TradingDate                  time.Time `gorm:"column:trading_date;type:date;primaryKey;comment:交易日期" json:"trading_date"`                                                           // 交易日期
	UpdatedAt                    time.Time `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`                                                                // 更新时间
}

// TableName StockStrong's table name
func (*StockStrong) TableName() string {
	return TableNameStockStrong
}
