// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStockDailyComment = "stock_daily_comment"

// StockDailyComment 每日股评列表-A股
type StockDailyComment struct {
	StockCode      string    `gorm:"column:stock_code;type:varchar(10);primaryKey;comment:股票代码" json:"stock_code"`                         // 股票代码
	StockName      string    `gorm:"column:stock_name;type:varchar(10);not null;comment:股票名称" json:"stock_name"`                           // 股票名称
	PlateType      int64     `gorm:"column:plate_type;type:tinyint(4);not null;comment:盘股类型(0-全部,1-微小盘,2-小盘,3-中盘,4-大盘)" json:"plate_type"` // 盘股类型(0-全部,1-微小盘,2-小盘,3-中盘,4-大盘)
	VolumeRatio    float64   `gorm:"column:volume_ratio;type:decimal(8,2);not null;default:0.00;comment:量比" json:"volume_ratio"`           // 量比
	TurnoverRate   float64   `gorm:"column:turnover_rate;type:decimal(8,2);not null;default:0.00;comment:换手" json:"turnover_rate"`         // 换手
	IncreaseRate   float64   `gorm:"column:increase_rate;type:decimal(8,2);not null;default:0.00;comment:涨幅" json:"increase_rate"`         // 涨幅
	CurrentPrice   float64   `gorm:"column:current_price;type:decimal(8,2);not null;default:0.00;comment:现价" json:"current_price"`         // 现价
	PrimeCost      float64   `gorm:"column:prime_cost;type:decimal(8,2);not null;default:0.00;comment:主力成本" json:"prime_cost"`             // 主力成本
	PrimeCost20    float64   `gorm:"column:prime_cost20;type:decimal(8,2);not null;default:0.00;comment:主力成本-20日" json:"prime_cost20"`     // 主力成本-20日
	PrimeCost60    float64   `gorm:"column:prime_cost60;type:decimal(8,2);not null;default:0.00;comment:主力成本-60日" json:"prime_cost60"`     // 主力成本-60日
	OrgParticipate float64   `gorm:"column:org_participate;type:decimal(8,2);not null;default:0.00;comment:机构参与度" json:"org_participate"`  // 机构参与度
	Score          float64   `gorm:"column:score;type:decimal(8,2);not null;default:0.00;comment:综合得分" json:"score"`                       // 综合得分
	Rank           int64     `gorm:"column:rank;type:int(11);not null;comment:综合得分排名" json:"rank"`                                         // 综合得分排名
	Focus          float64   `gorm:"column:focus;type:decimal(8,2);not null;default:0.00;comment:关注指数" json:"focus"`                       // 关注指数
	TradingDate    time.Time `gorm:"column:trading_date;type:date;primaryKey;comment:交易日期" json:"trading_date"`                            // 交易日期
	UpdatedAt      time.Time `gorm:"column:updated_at;autoUpdateTime:mill;comment:更新时间" json:"updated_at"`                                 // 更新时间
}

// TableName StockDailyComment's table name
func (*StockDailyComment) TableName() string {
	return TableNameStockDailyComment
}
