// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ocean386/stock-task/internal/orm/model"
)

func newStockFundsRank(db *gorm.DB, opts ...gen.DOOption) stockFundsRank {
	_stockFundsRank := stockFundsRank{}

	_stockFundsRank.stockFundsRankDo.UseDB(db, opts...)
	_stockFundsRank.stockFundsRankDo.UseModel(&model.StockFundsRank{})

	tableName := _stockFundsRank.stockFundsRankDo.TableName()
	_stockFundsRank.ALL = field.NewAsterisk(tableName)
	_stockFundsRank.StockCode = field.NewString(tableName, "stock_code")
	_stockFundsRank.StockName = field.NewString(tableName, "stock_name")
	_stockFundsRank.PlateType = field.NewInt64(tableName, "plate_type")
	_stockFundsRank.MainFund = field.NewFloat64(tableName, "main_fund")
	_stockFundsRank.MainPercent = field.NewFloat64(tableName, "main_percent")
	_stockFundsRank.SuperFund = field.NewFloat64(tableName, "super_fund")
	_stockFundsRank.SuperPercent = field.NewFloat64(tableName, "super_percent")
	_stockFundsRank.FundSortID = field.NewInt64(tableName, "fund_sort_id")
	_stockFundsRank.FundPercentSortID = field.NewInt64(tableName, "fund_percent_sort_id")
	_stockFundsRank.VolumeRatio = field.NewFloat64(tableName, "volume_ratio")
	_stockFundsRank.TurnoverRate = field.NewFloat64(tableName, "turnover_rate")
	_stockFundsRank.IncreaseRate = field.NewFloat64(tableName, "increase_rate")
	_stockFundsRank.CurrentPrice = field.NewFloat64(tableName, "current_price")
	_stockFundsRank.TradingDate = field.NewTime(tableName, "trading_date")
	_stockFundsRank.Industry = field.NewString(tableName, "industry")
	_stockFundsRank.IndustryCode = field.NewString(tableName, "industry_code")
	_stockFundsRank.UpdatedAt = field.NewTime(tableName, "updated_at")

	_stockFundsRank.fillFieldMap()

	return _stockFundsRank
}

// stockFundsRank 个股资金排行榜
type stockFundsRank struct {
	stockFundsRankDo

	ALL               field.Asterisk
	StockCode         field.String  // 股票代码
	StockName         field.String  // 股票名称
	PlateType         field.Int64   // 盘股类型(0-全部,1-小盘,2-中盘,3-大盘)
	MainFund          field.Float64 // 主力净流入(亿)
	MainPercent       field.Float64 // 主力净流入占比
	SuperFund         field.Float64 // 超大单净流入(亿)
	SuperPercent      field.Float64 // 超大单净流入占比
	FundSortID        field.Int64   // 净流入排名
	FundPercentSortID field.Int64   // 净占比排名
	VolumeRatio       field.Float64 // 量比
	TurnoverRate      field.Float64 // 换手
	IncreaseRate      field.Float64 // 涨幅
	CurrentPrice      field.Float64 // 现价
	TradingDate       field.Time    // 交易日期
	Industry          field.String  // 行业
	IndustryCode      field.String  // 行业代码
	UpdatedAt         field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (s stockFundsRank) Table(newTableName string) *stockFundsRank {
	s.stockFundsRankDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stockFundsRank) As(alias string) *stockFundsRank {
	s.stockFundsRankDo.DO = *(s.stockFundsRankDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stockFundsRank) updateTableName(table string) *stockFundsRank {
	s.ALL = field.NewAsterisk(table)
	s.StockCode = field.NewString(table, "stock_code")
	s.StockName = field.NewString(table, "stock_name")
	s.PlateType = field.NewInt64(table, "plate_type")
	s.MainFund = field.NewFloat64(table, "main_fund")
	s.MainPercent = field.NewFloat64(table, "main_percent")
	s.SuperFund = field.NewFloat64(table, "super_fund")
	s.SuperPercent = field.NewFloat64(table, "super_percent")
	s.FundSortID = field.NewInt64(table, "fund_sort_id")
	s.FundPercentSortID = field.NewInt64(table, "fund_percent_sort_id")
	s.VolumeRatio = field.NewFloat64(table, "volume_ratio")
	s.TurnoverRate = field.NewFloat64(table, "turnover_rate")
	s.IncreaseRate = field.NewFloat64(table, "increase_rate")
	s.CurrentPrice = field.NewFloat64(table, "current_price")
	s.TradingDate = field.NewTime(table, "trading_date")
	s.Industry = field.NewString(table, "industry")
	s.IndustryCode = field.NewString(table, "industry_code")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *stockFundsRank) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stockFundsRank) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 17)
	s.fieldMap["stock_code"] = s.StockCode
	s.fieldMap["stock_name"] = s.StockName
	s.fieldMap["plate_type"] = s.PlateType
	s.fieldMap["main_fund"] = s.MainFund
	s.fieldMap["main_percent"] = s.MainPercent
	s.fieldMap["super_fund"] = s.SuperFund
	s.fieldMap["super_percent"] = s.SuperPercent
	s.fieldMap["fund_sort_id"] = s.FundSortID
	s.fieldMap["fund_percent_sort_id"] = s.FundPercentSortID
	s.fieldMap["volume_ratio"] = s.VolumeRatio
	s.fieldMap["turnover_rate"] = s.TurnoverRate
	s.fieldMap["increase_rate"] = s.IncreaseRate
	s.fieldMap["current_price"] = s.CurrentPrice
	s.fieldMap["trading_date"] = s.TradingDate
	s.fieldMap["industry"] = s.Industry
	s.fieldMap["industry_code"] = s.IndustryCode
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s stockFundsRank) clone(db *gorm.DB) stockFundsRank {
	s.stockFundsRankDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stockFundsRank) replaceDB(db *gorm.DB) stockFundsRank {
	s.stockFundsRankDo.ReplaceDB(db)
	return s
}

type stockFundsRankDo struct{ gen.DO }

type IStockFundsRankDo interface {
	gen.SubQuery
	Debug() IStockFundsRankDo
	WithContext(ctx context.Context) IStockFundsRankDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStockFundsRankDo
	WriteDB() IStockFundsRankDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStockFundsRankDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStockFundsRankDo
	Not(conds ...gen.Condition) IStockFundsRankDo
	Or(conds ...gen.Condition) IStockFundsRankDo
	Select(conds ...field.Expr) IStockFundsRankDo
	Where(conds ...gen.Condition) IStockFundsRankDo
	Order(conds ...field.Expr) IStockFundsRankDo
	Distinct(cols ...field.Expr) IStockFundsRankDo
	Omit(cols ...field.Expr) IStockFundsRankDo
	Join(table schema.Tabler, on ...field.Expr) IStockFundsRankDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStockFundsRankDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStockFundsRankDo
	Group(cols ...field.Expr) IStockFundsRankDo
	Having(conds ...gen.Condition) IStockFundsRankDo
	Limit(limit int) IStockFundsRankDo
	Offset(offset int) IStockFundsRankDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStockFundsRankDo
	Unscoped() IStockFundsRankDo
	Create(values ...*model.StockFundsRank) error
	CreateInBatches(values []*model.StockFundsRank, batchSize int) error
	Save(values ...*model.StockFundsRank) error
	First() (*model.StockFundsRank, error)
	Take() (*model.StockFundsRank, error)
	Last() (*model.StockFundsRank, error)
	Find() ([]*model.StockFundsRank, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StockFundsRank, err error)
	FindInBatches(result *[]*model.StockFundsRank, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StockFundsRank) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStockFundsRankDo
	Assign(attrs ...field.AssignExpr) IStockFundsRankDo
	Joins(fields ...field.RelationField) IStockFundsRankDo
	Preload(fields ...field.RelationField) IStockFundsRankDo
	FirstOrInit() (*model.StockFundsRank, error)
	FirstOrCreate() (*model.StockFundsRank, error)
	FindByPage(offset int, limit int) (result []*model.StockFundsRank, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStockFundsRankDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stockFundsRankDo) Debug() IStockFundsRankDo {
	return s.withDO(s.DO.Debug())
}

func (s stockFundsRankDo) WithContext(ctx context.Context) IStockFundsRankDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stockFundsRankDo) ReadDB() IStockFundsRankDo {
	return s.Clauses(dbresolver.Read)
}

func (s stockFundsRankDo) WriteDB() IStockFundsRankDo {
	return s.Clauses(dbresolver.Write)
}

func (s stockFundsRankDo) Session(config *gorm.Session) IStockFundsRankDo {
	return s.withDO(s.DO.Session(config))
}

func (s stockFundsRankDo) Clauses(conds ...clause.Expression) IStockFundsRankDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stockFundsRankDo) Returning(value interface{}, columns ...string) IStockFundsRankDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stockFundsRankDo) Not(conds ...gen.Condition) IStockFundsRankDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stockFundsRankDo) Or(conds ...gen.Condition) IStockFundsRankDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stockFundsRankDo) Select(conds ...field.Expr) IStockFundsRankDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stockFundsRankDo) Where(conds ...gen.Condition) IStockFundsRankDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stockFundsRankDo) Order(conds ...field.Expr) IStockFundsRankDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stockFundsRankDo) Distinct(cols ...field.Expr) IStockFundsRankDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stockFundsRankDo) Omit(cols ...field.Expr) IStockFundsRankDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stockFundsRankDo) Join(table schema.Tabler, on ...field.Expr) IStockFundsRankDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stockFundsRankDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStockFundsRankDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stockFundsRankDo) RightJoin(table schema.Tabler, on ...field.Expr) IStockFundsRankDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stockFundsRankDo) Group(cols ...field.Expr) IStockFundsRankDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stockFundsRankDo) Having(conds ...gen.Condition) IStockFundsRankDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stockFundsRankDo) Limit(limit int) IStockFundsRankDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stockFundsRankDo) Offset(offset int) IStockFundsRankDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stockFundsRankDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStockFundsRankDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stockFundsRankDo) Unscoped() IStockFundsRankDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stockFundsRankDo) Create(values ...*model.StockFundsRank) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stockFundsRankDo) CreateInBatches(values []*model.StockFundsRank, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stockFundsRankDo) Save(values ...*model.StockFundsRank) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stockFundsRankDo) First() (*model.StockFundsRank, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockFundsRank), nil
	}
}

func (s stockFundsRankDo) Take() (*model.StockFundsRank, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockFundsRank), nil
	}
}

func (s stockFundsRankDo) Last() (*model.StockFundsRank, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockFundsRank), nil
	}
}

func (s stockFundsRankDo) Find() ([]*model.StockFundsRank, error) {
	result, err := s.DO.Find()
	return result.([]*model.StockFundsRank), err
}

func (s stockFundsRankDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StockFundsRank, err error) {
	buf := make([]*model.StockFundsRank, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stockFundsRankDo) FindInBatches(result *[]*model.StockFundsRank, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stockFundsRankDo) Attrs(attrs ...field.AssignExpr) IStockFundsRankDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stockFundsRankDo) Assign(attrs ...field.AssignExpr) IStockFundsRankDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stockFundsRankDo) Joins(fields ...field.RelationField) IStockFundsRankDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stockFundsRankDo) Preload(fields ...field.RelationField) IStockFundsRankDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stockFundsRankDo) FirstOrInit() (*model.StockFundsRank, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockFundsRank), nil
	}
}

func (s stockFundsRankDo) FirstOrCreate() (*model.StockFundsRank, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockFundsRank), nil
	}
}

func (s stockFundsRankDo) FindByPage(offset int, limit int) (result []*model.StockFundsRank, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stockFundsRankDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stockFundsRankDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stockFundsRankDo) Delete(models ...*model.StockFundsRank) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stockFundsRankDo) withDO(do gen.Dao) *stockFundsRankDo {
	s.DO = *do.(*gen.DO)
	return s
}
